
version: "2"

run:
    concurrency: 6 # INFO: depends on your dev environment
    tests: true    # INFO: developer preference (depends on project)

linters:
    default: none
    enable:
        - bodyclose
        - errcheck
        - errname
        - errorlint
        - exhaustive
        - gosec
        - govet
        - ineffassign
        - makezero
        - nakedret
        - nolintlint
        - sqlclosecheck
        - staticcheck
        - tparallel
        - unconvert
        - unparam
        - unused
        - usestdlibvars
        - wastedassign
    settings:
        exhaustive:
            default-signifies-exhaustive: true
        nakedret:
          # I don't like naked returns
          max-func-lines: 0
        errcheck:
            check-type-assertions: true
            # assignment to blank is considered 'handled'
            check-blank: false
        govet:
            enable-all: true
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
        rules:
            - linters:
                - errcheck
              # disable checking defer funcs for unhandled err's
              source: '^\s*defer\s'

issues:
    max-issues-per-linter: 0
    max-same-issues: 0

formatters:
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
