
version: "2"
run:
    concurrency: 6
    tests: true
linters:
    default: none
    enable:
        - errcheck
        # - goconst
        - govet
        - ineffassign
        - staticcheck
        - unused
    settings:
        goconst:
            ignore-tests: true
        errcheck:
            check-type-assertions: true
            check-blank: true
        govet:
            disable:
                - fieldalignment
            enable-all: true
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
        rules:
            - linters:
                - errcheck
              source: '^\s*defer\s'
issues:
    max-issues-per-linter: 0
    max-same-issues: 0
formatters:
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
