
version: "2"
run:
    concurrency: 6 # TODO: change this to match your system
    tests: true
linters:
    default: none
    enable:
        - errcheck
        - bodyclose
        - exhaustive
        - sqlclosecheck
        - makezero
        - nolintlint
        - unparam
        - unconvert
        - usestdlibvars
        - gosec
        - errname
        - tparallel
        - nakedret
        - errorlint
        - govet
        - ineffassign
        - staticcheck
        - wastedassign
        - unused
    settings:
        nakedret:
          max-func-lines: 0
        errcheck:
            check-type-assertions: true
            # assignment to blank is considered 'handled'
            check-blank: false
        govet:
            disable:
                - fieldalignment
            enable-all: true
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
        rules:
            - linters:
                - errcheck
              source: '^\s*defer\s'
issues:
    max-issues-per-linter: 0
    max-same-issues: 0
formatters:
    exclusions:
        generated: lax
        paths:
            - third_party$
            - builtin$
            - examples$
